version: "3"

volumes:
  influxdb:
    driver: "local"

services:
  grafana:
    image: "grafana/grafana"
#    context: ./grafana
    ports:
      - "8080:3000"
    environment:
      - INFLUXDB_URL=http://influxdb:9999
    links:
      - influxdb

  influxdb:
    image: "quay.io/influxdb/influxdb:2.0.0-alpha"
    ports:
      - "9999:9999"
    volumes:
      - influxdb

  chronograf:
#    image: "quay.io/influxdb/chronograf:1.7.12"
    image: chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:9999
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=12345678
      - LOG_LEVEL=debug
